name: Go
on: [push, pull_request]
jobs:

  build:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.13]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        make test-coverage
        cp coverage.txt coverage.out
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert coverage file
      run: go run -v github.com/jandelgado/gcov2lcov -infile=coverage.txt -outfile=lcov.info

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./lcov.info
