name: Go
on: [push, pull_request]
jobs:

  build:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.13]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        make test-coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage
      run: |
        os=$(echo ${{ matrix.os }} | tr '[:punct:]' '_')
        go=$(echo ${{ matrix.go_version }} | tr '[:punct:]' '_')
        bash <(curl -s https://codecov.io/bash) -f coverage.txt -cF $os,$go
      env:
        CODECOV_TOKEN: 8d59413b-e9ed-47d5-ba27-86b27e3f4bee
